### PR TITLE
Fix the GHC 8.2 build by using a simple Setup.hs

### PR DESCRIPTION
**Pull request by RyanGlScott**
`quine` would build on GHC 8.2 were it not for the custom `Setup.hs` script:

```
$ cabal configure --enable-tests --enable-benchmarks -w ~/Software/ghc/inplace/bin/ghc-stage2 --allow-newer
Resolving dependencies...
[1 of 1] Compiling Main             ( dist/setup/setup.hs, dist/setup/Main.o )

dist/setup/setup.hs:8:31: error:
    Module
    ‘Distribution.Package’
    does not export
    ‘PackageName(PackageName)’
  |
8 | import Distribution.Package ( PackageName(PackageName), PackageId, InstalledPackageId, packageVersion, packageName )
  |                               ^^^^^^^^^^^^^^^^^^^^^^^^
```

But as far as I can tell, using a custom `Cabal` build type is completely unnecessary here, as `quine` doesn't actually use `doctests`! So I opted for the simple solution of just using a simple `Setup.hs` script instead.

### CODE REVIEW

**Comment by ekmett** [comment]
Easy enough. doctest was preëmptive. Once I figured out what the API was going to look like, I'd intended to put them in.

**Comment by RyanGlScott** [comment]
Ah, OK. Do bear in mind that eventually integrating `doctest` into `quine` might prove difficult since, at the moment, `doctest` and `hsc2hs` [don't mix well](https://github.com/phadej/cabal-doctest/issues/8).

**Comment by ekmett** [comment]
Then I guess we'll pay that tax when we get around to it. =)
